"""drop url

Revision ID: 509fccda74d3
Revises: 1ea6ddf58753
Create Date: 2018-04-25 22:05:15.880692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '509fccda74d3'
down_revision = '1ea6ddf58753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('url', mysql.VARCHAR(collation='utf8_unicode_ci', length=1000), nullable=True))
    # ### end Alembic commands ###
