"""editing feed column

Revision ID: a672063cafeb
Revises: bba18d44f52c
Create Date: 2018-04-26 02:04:50.399872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a672063cafeb'
down_revision = 'bba18d44f52c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('editing_feed_id', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'editing_feed_id')
    # ### end Alembic commands ###
