"""add chat hanling fields

Revision ID: bba18d44f52c
Revises: e0f645a35a86
Create Date: 2018-04-26 01:40:12.667011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bba18d44f52c'
down_revision = 'e0f645a35a86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('state', sa.String(length=32), nullable=True))
    op.add_column('feed', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed', 'name')
    op.drop_column('chat', 'state')
    # ### end Alembic commands ###
