"""drom updated column

Revision ID: e0f645a35a86
Revises: fa662e5f78a6
Create Date: 2018-04-26 01:08:50.148879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e0f645a35a86'
down_revision = 'fa662e5f78a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('updated', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
