"""long url

Revision ID: fa662e5f78a6
Revises: 509fccda74d3
Create Date: 2018-04-25 22:09:03.273059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa662e5f78a6'
down_revision = '509fccda74d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed', 'url')
    # ### end Alembic commands ###
