"""fix

Revision ID: fafc98204da6
Revises: b341f9ae9495
Create Date: 2018-04-26 03:32:24.213833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fafc98204da6'
down_revision = 'b341f9ae9495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('author', sa.String(length=255), nullable=True))
    op.add_column('entry', sa.Column('title', sa.String(length=255), nullable=True))
    op.drop_column('feed', 'title')
    op.drop_column('feed', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('author', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=True))
    op.add_column('feed', sa.Column('title', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=True))
    op.drop_column('entry', 'title')
    op.drop_column('entry', 'author')
    # ### end Alembic commands ###
